name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.x
      - run: bun install --frozen-lockfile
      - run: bunx biome ci src
      - run: bun test
